// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/font/Arsenal-Bold.ttf"
    | "/font/Arsenal-BoldItalic.ttf"
    | "/font/Arsenal-Italic.ttf"
    | "/font/Arsenal-Regular.ttf"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/illustration/relax.png"
    | "/illustration/welcome.svg"
    | "/welcome.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
